-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               11.5.2-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             12.6.0.6765
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping database structure for flight
CREATE DATABASE IF NOT EXISTS `flight` /*!40100 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci */;
USE `flight`;

-- Dumping structure for table flight.bookings
CREATE TABLE IF NOT EXISTS `bookings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `airline` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `class` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `airPlaneLogoImg` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `bookingCode` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `fullName` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `dob` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `gender` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `citizenID` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci DEFAULT NULL,
  `birthCertificate` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci DEFAULT NULL,
  `expirationDate` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci DEFAULT NULL,
  `address` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci DEFAULT NULL,
  `phone` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci DEFAULT NULL,
  `startPlace` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `endPlace` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `startPlaceFullName` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `endPlaceFullName` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `startPlaceAirportVNLang` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `startPlaceAirportENLang` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `endPlaceAirportVNLang` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `endPlaceAirportENLang` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `timeStart` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `timeEnd` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `duration` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `price` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `direct` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `carryOnBaggage` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `checkedBaggage` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `flightNumber` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `website` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `adult` int(11) NOT NULL DEFAULT 0,
  `child` int(11) NOT NULL DEFAULT 0,
  `totalPassenger` int(11) NOT NULL,
  `departureDate` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `seat` varchar(50) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `gate` varchar(50) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `qrCodeImg` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci DEFAULT NULL,
  `username` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=154 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

-- Dumping data for table flight.bookings: ~0 rows (approximately)

-- Dumping structure for table flight.flights
CREATE TABLE IF NOT EXISTS `flights` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `logo` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `airlineImage` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `timeStart` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `timeEnd` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `startPlaceFullname` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `startPlace` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `startPlaceAirportVNLang` varchar(500) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `startPlaceAirportENLang` varchar(500) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `endPlaceFullname` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `endPlace` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `endPlaceAirportVNLang` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `endPlaceAirportENLang` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `airline` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `duration` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `originalPrice` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `discountPrice` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `direct` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `class` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `carryOnBaggage` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `checkedBaggage` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `notePrice` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci DEFAULT NULL,
  `noteFast` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci DEFAULT NULL,
  `flightNumber` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `website` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=127 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

-- Dumping data for table flight.flights: ~114 rows (approximately)
INSERT INTO `flights` (`id`, `logo`, `airlineImage`, `timeStart`, `timeEnd`, `startPlaceFullname`, `startPlace`, `startPlaceAirportVNLang`, `startPlaceAirportENLang`, `endPlaceFullname`, `endPlace`, `endPlaceAirportVNLang`, `endPlaceAirportENLang`, `airline`, `duration`, `originalPrice`, `discountPrice`, `direct`, `class`, `carryOnBaggage`, `checkedBaggage`, `notePrice`, `noteFast`, `flightNumber`, `website`) VALUES
	(1, 'https://i.postimg.cc/ZYytchFh/vietjet-Air.png', 'https://i.postimg.cc/BbWqgZjX/Vietjet-Air-Airplane-removebg-preview.png', '06:00', '08:00', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Hà Nội', 'HAN', 'Sân bay Quốc tế Nội Bài', 'Noi Bai International Airport', 'Vietjet Air', '2h00m', '1.120.090', '1.052.000', 'Direct', 'Basic', '1 piece per person, 10kg per piece', '10kg per item', 'Cheapest', '', 'VJ 415', 'https://www.vietjetair.com/'),
	(2, 'https://i.postimg.cc/ZYytchFh/vietjet-Air.png', 'https://i.postimg.cc/BbWqgZjX/Vietjet-Air-Airplane-removebg-preview.png"', '07:00', '08:45', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Hà Nội', 'HAN', 'Sân bay Quốc tế Nội Bài', 'Noi Bai International Airport', 'Vietjet Air', '1h45m', '1.135.978', '1.087.232', 'Direct', 'Basic', '1 piece per person, 10kg per piece', '10kg per item', '', 'Fastest', 'VJ 416', 'https://www.vietjetair.com/'),
	(3, 'https://i.postimg.cc/NGN8Sf9V/Vn-Airlines.png', 'https://i.postimg.cc/nrxWWVXM/Vn-Airlines-Airplane-removebg-preview.png', '07:30', '09:25', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Hà Nội', 'HAN', 'Sân bay Quốc tế Nội Bài', 'Noi Bai International Airport', 'Vietnam Airlines', '1h55m', '1.989.232', '1.921.909', 'Direct', 'Basic', '1 piece per person, 10kg per piece', '23kg per item', 'Cheapest', 'Fastest', 'VN 1000', 'https://www.vietnamairlines.com/'),
	(4, 'https://i.postimg.cc/NGN8Sf9V/Vn-Airlines.png', 'https://i.postimg.cc/nrxWWVXM/Vn-Airlines-Airplane-removebg-preview.png', '08:00', '10:10', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Hà Nội', 'HAN', 'Sân bay Quốc tế Nội Bài', 'Noi Bai International Airport', 'Vietnam Airlines', '2h10m', '2.094.909', '2.052.090', 'Direct', 'Basic', '1 piece per person, 10kg per piece', '23kg per item', 'Cheapest', '', 'VN 1001', 'https://www.vietnamairlines.com/'),
	(6, 'https://i.postimg.cc/VkJV5mkh/Bamboo-Airways-logo-removebg-preview.png', 'https://i.postimg.cc/C5ycZqdr/bamboo-airways-1-676-1481-removebg-preview.png', '09:10', '11:15', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Hà Nội', 'HAN', 'Sân bay Quốc tế Nội Bài', 'Noi Bai International Airport', 'Bamboo Airways', '2h05m', '2.057.232', '2.021.909', 'Direct', 'Basic', '1 piece per person, 10kg per piece', '20kg per item', 'Cheapest', '', 'QH 226', 'https://www.bambooairways.com/'),
	(7, 'https://i.postimg.cc/X7Mm9Rcs/Scoot-Airline-logo-removebg-preview.png', 'https://i.postimg.cc/mgjY29gQ/Scoot-Airlines-airplane-removebg-preview.png', '09:35', '11:45', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Hà Nội', 'HAN', 'Sân bay Quốc tế Nội Bài', 'Noi Bai International Airport', 'Scoot Airlines', '2h10m', '2.219.290', '2.152.909', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '25kg per item', '', '', 'TR 979', 'https://flights.flyscoot.com/'),
	(8, 'https://i.postimg.cc/CKPL1h8P/Singapore-Airlines-Logo-removebg-preview.png', 'https://i.postimg.cc/tJdKskfq/Singapore-Airlines-airplane-removebg-preview.png', '10:00', '12:05', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Hà Nội', 'HAN', 'Sân bay Quốc tế Nội Bài', 'Noi Bai International Airport', 'Singapore Airlines', '2h05m', '2.231.090', '2.154.343', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '25kg per item', '', 'Comfort', 'SQ 877', 'https://www.singaporeair.com/'),
	(9, 'https://i.postimg.cc/RFd1qndr/Air-Seoul-South-Korea-logo-removebg-preview.png', 'https://i.postimg.cc/WbXyxdcH/Air-Seoul-airplane-removebg-preview-1.png', '10:30', '12:30', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Hà Nội', 'HAN', 'Sân bay Quốc tế Nội Bài', 'Noi Bai International Airport', 'Air Seoul', '2h00m', '1.423.342', '1.370.787', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '15kg per item', '', 'Comfort', 'RS 1029', 'https://flyairseoul.com/'),
	(10, 'https://i.postimg.cc/ZYytchFh/vietjet-Air.png', 'https://i.postimg.cc/BbWqgZjX/Vietjet-Air-Airplane-removebg-preview.png', '11:00', '13:04', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Hà Nội', 'HAN', 'Sân bay Quốc tế Nội Bài', 'Noi Bai International Airport', 'Vietjet Air', '2h04m', '1.419.232', '1.363.954', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '15kg per item', '', '', 'VJ 231', 'https://www.vietjetair.com/'),
	(11, 'https://i.postimg.cc/QCKYMrsD/Vietravel-Airlines-Logo.png', 'https://i.postimg.cc/3wJTxWqH/viet-Travel-Airplane-removebg-preview.png', '11:30', '13:30', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Hà Nội', 'HAN', 'Sân bay Quốc tế Nội Bài', 'Noi Bai International Airport', 'Vietravel Airlines', '2h00m', '1.652.292', '1.598.989', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '15kg per item', '', '', 'VU 751', 'https://www.vietravelairlines.com/'),
	(12, 'https://i.postimg.cc/QCKYMrsD/Vietravel-Airlines-Logo.png', 'https://i.postimg.cc/3wJTxWqH/viet-Travel-Airplane-removebg-preview.png', '12:00', '14:00', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Hà Nội', 'HAN', 'Sân bay Quốc tế Nội Bài', 'Noi Bai International Airport', 'Vietravel Airlines', '2h00m', '1.652.292', '1.598.989', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '15kg per item', '', '', 'VU 781', 'https://www.vietravelairlines.com/'),
	(13, 'https://i.postimg.cc/ZYytchFh/vietjet-Air.png', 'https://i.postimg.cc/BbWqgZjX/Vietjet-Air-Airplane-removebg-preview.png', '12:40', '14:50', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Hà Nội', 'HAN', 'Sân bay Quốc tế Nội Bài', 'Noi Bai International Airport', 'Vietjet Air', '2h10m', '1.415.232', '1.365.954', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '15kg per item', '', '', 'VJ 219', 'https://www.vietjetair.com/'),
	(14, 'https://i.postimg.cc/VkJV5mkh/Bamboo-Airways-logo-removebg-preview.png', 'https://i.postimg.cc/C5ycZqdr/bamboo-airways-1-676-1481-removebg-preview.png', '13:30', '15:45', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Hà Nội', 'HAN', 'Sân bay Quốc tế Nội Bài', 'Noi Bai International Airport', 'Bamboo Airways', '1h55m', '2.040.232', '2.000.909', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '20kg per item', '', '', 'QH 230', 'https://www.bambooairways.com/'),
	(15, 'https://i.postimg.cc/VkJV5mkh/Bamboo-Airways-logo-removebg-preview.png', 'https://i.postimg.cc/C5ycZqdr/bamboo-airways-1-676-1481-removebg-preview.png', '13:50', '16:00', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Hà Nội', 'HAN', 'Sân bay Quốc tế Nội Bài', 'Noi Bai International Airport', 'Bamboo Airways', '2h10m', '2.010.232', '1.965.232', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '20kg per item', '', '', 'QH 240', 'https://www.bambooairways.com/'),
	(16, 'https://i.postimg.cc/xdmsJpjQ/Cambodia-Angkor-Air-Cambodia-removebg-preview.png', 'https://i.postimg.cc/TYhpJZzr/Cambodia-Angkor-Air-airplane-removebg-preview.png', '14:30', '17:00', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Hà Nội', 'HAN', 'Sân bay Quốc tế Nội Bài', 'Noi Bai International Airport', 'Cambodia Angkor Air', '2h30m', '4.098.202', '4.010.569', 'Direct', 'Business', '1 piece per person, 20kg per piece', '30kg per item', '', '', 'K6 813', 'https://www.cambodiaangkorair.com/'),
	(18, 'https://i.postimg.cc/xdmsJpjQ/Cambodia-Angkor-Air-Cambodia-removebg-preview.png', 'https://i.postimg.cc/TYhpJZzr/Cambodia-Angkor-Air-airplane-removebg-preview.png', '15:00', '17:25', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Hà Nội', 'HAN', 'Sân bay Quốc tế Nội Bài', 'Noi Bai International Airport', 'Cambodia Angkor Air', '2h25m', '4.108.909', '4.020.592', 'Direct', 'Business', '1 piece per person, 20kg per piece', '30kg per item', '', '', 'K6 816', 'https://www.cambodiaangkorair.com/'),
	(19, 'https://i.postimg.cc/L6wtqSts/Delta-Air-Lines-logos-removebg-preview.png', 'https://i.postimg.cc/5yZXtxhd/Delta-Air-Lines-airplane-removebg-preview-1.png', '15:30', '17:45', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Hà Nội', 'HAN', 'Sân bay Quốc tế Nội Bài', 'Noi Bai International Airport', 'Delta Airlines', '2h15m', '7.221.453', '7.199.232', 'Direct', 'Business', '1 piece per person, 10kg per piece', '30kg per item', '', 'Comfort', 'DL 878', 'https://www.delta.com/'),
	(20, 'https://i.postimg.cc/NGN8Sf9V/Vn-Airlines.png', 'https://i.postimg.cc/nrxWWVXM/Vn-Airlines-Airplane-removebg-preview.png', '16:10', '18:20', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Hà Nội', 'HAN', 'Sân bay Quốc tế Nội Bài', 'Noi Bai International Airport', 'Vietnam Airlines', '2h10m', '3.225.453', '2.203.232', 'Direct', 'Business', '1 piece per person, 10kg per piece', '25kg per item', '', '', 'VN 879', 'https://www.vietnamairlines.com/'),
	(26, 'https://i.postimg.cc/ZRtbtq5S/Cathay-Pacific-Airways-logo-removebg-preview.png', 'https://i.postimg.cc/nzGtyYW4/Cathay-pacific-airplane-removebg-preview.png', '19:00', '21:30', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Hà Nội', 'HAN', 'Sân bay Quốc tế Nội Bài', 'Noi Bai International Airport', 'Cathay Pacific', '2h30m', '9.241.901', '9.220.878', 'Direct', 'Premium ', '1 piece per person, 25kg per piece', '35kg per item', '', '', 'CX 1000', 'https://www.cathaypacific.com/'),
	(27, 'https://i.postimg.cc/ZRtbtq5S/Cathay-Pacific-Airways-logo-removebg-preview.png', 'https://i.postimg.cc/nzGtyYW4/Cathay-pacific-airplane-removebg-preview.png', '20:00', '22:30', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Hà Nội', 'HAN', 'Sân bay Quốc tế Nội Bài', 'Noi Bai International Airport', 'Cathay Pacific', '2h30m', '9.451.121', '9.410.978', 'Direct', 'Premium ', '1 piece per person, 25kg per piece', '35kg per item', '', '', 'CX 1001', 'https://www.cathaypacific.com/'),
	(28, 'https://i.postimg.cc/wBCJvQLb/China-Southern-Airlines-logo-removebg-preview.png', 'https://i.postimg.cc/8zTZkNNr/China-Southern-Airlines-airplane-removebg-preview.png', '20:45', '22:55', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Hà Nội', 'HAN', 'Sân bay Quốc tế Nội Bài', 'Noi Bai International Airport', 'China Southen Airlines', '2h10m', '7.302.981', '7.263.901', 'Direct', 'Premium ', '1 piece per person, 10kg per piece', '25kg per item', '', 'Comfort', 'CZ 880', 'https://oversea.csair.com/'),
	(29, 'https://i.postimg.cc/NGN8Sf9V/Vn-Airlines.png', 'https://i.postimg.cc/nrxWWVXM/Vn-Airlines-Airplane-removebg-preview.png', '21:35', '23:35', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Hà Nội', 'HAN', 'Sân bay Quốc tế Nội Bài', 'Noi Bai International Airport', 'Vietnam Airlines', '2h00m', '7.352.981', '7.823.901', 'Direct', 'Premium ', '1 piece per person, 10kg per piece', '25kg per item', '', '', 'VN 881', 'https://www.vietnamairlines.com/'),
	(30, 'https://i.postimg.cc/NGN8Sf9V/Vn-Airlines.png', 'https://i.postimg.cc/nrxWWVXM/Vn-Airlines-Airplane-removebg-preview.png', '22:00', '00:00', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Hà Nội', 'HAN', 'Sân bay Quốc tế Nội Bài', 'Noi Bai International Airport', 'Vietnam Airlines', '2h00m', '7.352.981', '7.823.901', 'Direct', 'Premium ', '1 piece per person, 10kg per piece', '25kg per item', '', '', 'VN 882', 'https://www.vietnamairlines.com/'),
	(31, 'https://i.postimg.cc/MGSn8tTH/emitares-airline-logo.png', 'https://i.postimg.cc/0NxTvJqP/emirates-airplane.png', '22:45', '01:10', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Hà Nội', 'HAN', 'Sân bay Quốc tế Nội Bài', 'Noi Bai International Airport', 'Emirates Airline', '2h30m', '13.092.090', '13.010.634', 'Direct', 'Premium ', '1 piece per person, 25kg per piece', '50kg per item', 'Deluxe', 'Comfort', 'EK 100', 'https://www.emirates.com/'),
	(32, 'https://i.postimg.cc/MGSn8tTH/emitares-airline-logo.png', 'https://i.postimg.cc/0NxTvJqP/emirates-airplane.png', '23:00', '01:30', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Hà Nội', 'HAN', 'Sân bay Quốc tế Nội Bài', 'Noi Bai International Airport', 'Emirates Airline', '2h30m', '13.092.090', '13.010.634', 'Direct', 'Premium ', '1 piece per person, 25kg per piece', '50kg per item', 'Deluxe', 'Comfort', 'EK 101', 'https://www.emirates.com/'),
	(33, 'https://i.postimg.cc/vBdHpvQh/EVA-Air-logo-removebg-preview.png', 'https://i.postimg.cc/DfNsMt9P/EVA-airplane-removebg-preview.png', '23:30', '02:00', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Hà Nội', 'HAN', 'Sân bay Quốc tế Nội Bài', 'Noi Bai International Airport', 'EVA Air', '2h30m', '12.438.928', '12.401.266', 'Direct', 'Premium ', '1 piece per person, 20kg per piece', '35kg per item', '', 'Comfort', 'BR 1000', 'https://www.evaair.com/'),
	(34, 'https://i.postimg.cc/vBdHpvQh/EVA-Air-logo-removebg-preview.png', 'https://i.postimg.cc/DfNsMt9P/EVA-airplane-removebg-preview.png', '01:00', '03:05', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Hà Nội', 'HAN', 'Sân bay Quốc tế Nội Bài', 'Noi Bai International Airport', 'EVA Air', '2h05m', '12.420.928', '12.405.266', 'Direct', 'Business', '1 piece per person, 20kg per piece', '35kg per item', '', 'Comfort', 'BR 791', 'https://www.evaair.com/'),
	(35, 'https://i.postimg.cc/QCKYMrsD/Vietravel-Airlines-Logo.png', 'https://i.postimg.cc/3wJTxWqH/viet-Travel-Airplane-removebg-preview.png', '01:05', '03:10', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Hà Nội', 'HAN', 'Sân bay Quốc tế Nội Bài', 'Noi Bai International Airport', 'Vietravel Airlines', '2h05m', '2.240.202', '2.204.129', 'Direct', 'Business', '1 piece per person, 10kg per piece', '15kg per item', '', '', 'VU 801', 'https://www.vietravelairlines.com/'),
	(36, 'https://i.postimg.cc/t4zWg7c9/Jetstar-Pacific-logo-removebg-preview.png', 'https://i.postimg.cc/Bvx5HMtf/Jetstar-Pacific-airplane-removebg-preview.png', '03:00', '05:00', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Hà Nội', 'HAN', 'Sân bay Quốc tế Nội Bài', 'Noi Bai International Airport', 'Jetstar Pacific', '2h00m', '2.140.202', '2.104.129', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '15kg per item', '', '', 'BL 1000', 'https://www.jetstar.com/'),
	(37, 'https://i.postimg.cc/ZYytchFh/vietjet-Air.png', 'https://i.postimg.cc/BbWqgZjX/Vietjet-Air-Airplane-removebg-preview.png', '03:30', '05:30', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Hà Nội', 'HAN', 'Sân bay Quốc tế Nội Bài', 'Noi Bai International Airport', 'Vietjet Air', '2h00m', '1.652.292', '1.598.989', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '15kg per item', '', '', 'VJ 6768', 'https://www.vietjetair.com/'),
	(38, 'https://i.postimg.cc/ZYytchFh/vietjet-Air.png', 'https://i.postimg.cc/BbWqgZjX/Vietjet-Air-Airplane-removebg-preview.png', '09:30', '10:40', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Đà Nẵng', 'DAD', 'Sân bay Quốc tế Đà Nẵng', 'Da Nang International Airport', 'Vietjet Air', '1h10m', '762.210', '755.991', 'Direct', 'Basic', '1 piece per person, 10kg per piece', '15kg per item', 'Cheapest', '', 'VJ 6769', 'https://www.vietjetair.com/'),
	(39, 'https://i.postimg.cc/ZYytchFh/vietjet-Air.png', 'https://i.postimg.cc/BbWqgZjX/Vietjet-Air-Airplane-removebg-preview.png', '11:35', '12:25', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Đà Nẵng', 'DAD', 'Sân bay Quốc tế Đà Nẵng', 'Da Nang International Airport', 'Vietjet Air', '0h50m', '792.019', '785.921', 'Direct', 'Basic', '1 piece per person, 10kg per piece', '15kg per item', 'Cheapest', 'Fastest', 'VJ 6770', 'https://www.vietjetair.com/'),
	(40, 'https://i.postimg.cc/ZYytchFh/vietjet-Air.png', 'https://i.postimg.cc/BbWqgZjX/Vietjet-Air-Airplane-removebg-preview.png', '13:25', '14:30', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Đà Nẵng', 'DAD', 'Sân bay Quốc tế Đà Nẵng', 'Da Nang International Airport', 'Vietjet Air', '1h05m', '982.313', '971.201', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '15kg per item', '', '', 'VJ 6771', 'https://www.vietjetair.com/'),
	(41, 'https://i.postimg.cc/NGN8Sf9V/Vn-Airlines.png', 'https://i.postimg.cc/nrxWWVXM/Vn-Airlines-Airplane-removebg-preview.png', '14:45', '15:50', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Đà Nẵng', 'DAD', 'Sân bay Quốc tế Đà Nẵng', 'Da Nang International Airport', 'Vietnam Airlines', '1h05m', '1.277.021', '1.250.291', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '25kg per item', '', '', 'VN 883', 'https://www.vietnamairlines.com/'),
	(42, 'https://i.postimg.cc/NGN8Sf9V/Vn-Airlines.png', 'https://i.postimg.cc/nrxWWVXM/Vn-Airlines-Airplane-removebg-preview.png', '16:30', '17:40', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Đà Nẵng', 'DAD', 'Sân bay Quốc tế Đà Nẵng', 'Da Nang International Airport', 'Vietnam Airlines', '1h10m', '1.322.310', '1.300.212', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '25kg per item', '', '', 'VN 884', 'https://www.vietnamairlines.com/'),
	(43, 'https://i.postimg.cc/QCKYMrsD/Vietravel-Airlines-Logo.png', 'https://i.postimg.cc/3wJTxWqH/viet-Travel-Airplane-removebg-preview.png', '18:15', '19:20', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Đà Nẵng', 'DAD', 'Sân bay Quốc tế Đà Nẵng', 'Da Nang International Airport', 'Vietravel Airlines', '1h05m', '1.217.092', '1.200.023', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '15kg per item', '', '', 'VU 811', 'https://www.vietravelairlines.com/'),
	(44, 'https://i.postimg.cc/QCKYMrsD/Vietravel-Airlines-Logo.png', 'https://i.postimg.cc/3wJTxWqH/viet-Travel-Airplane-removebg-preview.png', '19:30', '20:40', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Đà Nẵng', 'DAD', 'Sân bay Quốc tế Đà Nẵng', 'Da Nang International Airport', 'Vietravel Airlines', '1h10m', '1.352.910', '1.320.892', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '15kg per item', '', '', 'VU 812', 'https://www.vietravelairlines.com/'),
	(45, 'https://i.postimg.cc/t4zWg7c9/Jetstar-Pacific-logo-removebg-preview.png', 'https://i.postimg.cc/Bvx5HMtf/Jetstar-Pacific-airplane-removebg-preview.png', '21:05', '22:05', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Đà Nẵng', 'DAD', 'Sân bay Quốc tế Đà Nẵng', 'Da Nang International Airport', 'Jetstar Pacific', '1h00m', '1.421.910', '1.407.812', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '15kg per item', '', '', 'BL 1001', 'https://www.jetstar.com/'),
	(46, 'https://i.postimg.cc/VkJV5mkh/Bamboo-Airways-logo-removebg-preview.png', 'https://i.postimg.cc/C5ycZqdr/bamboo-airways-1-676-1481-removebg-preview.png', '22:35', '23:40', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Đà Nẵng', 'DAD', 'Sân bay Quốc tế Đà Nẵng', 'Da Nang International Airport', 'Bamboo Airways', '1h05m', '1.724.901', '1.700.021', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '20kg per item', '', '', 'QH 961', 'https://www.bambooairways.com/'),
	(47, 'https://i.postimg.cc/ZYytchFh/vietjet-Air.png', 'https://i.postimg.cc/BbWqgZjX/Vietjet-Air-Airplane-removebg-preview.png', '06:05', '07:00', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Nha Trang', 'CXR', 'Sân bay Quốc tế Cam Ranh', 'Cam Ranh International Airport', 'Vietjet Air', '0h55m', '681.091', '670.012', 'Direct', 'Basic', '1 piece per person, 10kg per piece', '15kg per item', 'Cheapest', 'Fastest', 'VJ 274', 'https://www.vietjetair.com/'),
	(48, 'https://i.postimg.cc/ZYytchFh/vietjet-Air.png', 'https://i.postimg.cc/BbWqgZjX/Vietjet-Air-Airplane-removebg-preview.png', '07:40', '08:50', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Nha Trang', 'CXR', 'Sân bay Quốc tế Cam Ranh', 'Cam Ranh International Airport', 'Vietjet Air', '1h10m', '742.012', '730.277', 'Direct', 'Basic', '1 piece per person, 10kg per piece', '15kg per item', 'Cheapest', '', 'VJ 1321', 'https://www.vietjetair.com/'),
	(49, 'https://i.postimg.cc/VkJV5mkh/Bamboo-Airways-logo-removebg-preview.png', 'https://i.postimg.cc/C5ycZqdr/bamboo-airways-1-676-1481-removebg-preview.png', '09:45', '10:55', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Nha Trang', 'CXR', 'Sân bay Quốc tế Cam Ranh', 'Cam Ranh International Airport', 'Bamboo Airways', '1h10m', '1.332.019', '1.310.201', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '20kg per item', '', '', 'QH 2322', 'https://www.bambooairways.com/'),
	(50, 'https://i.postimg.cc/VkJV5mkh/Bamboo-Airways-logo-removebg-preview.png', 'https://i.postimg.cc/C5ycZqdr/bamboo-airways-1-676-1481-removebg-preview.png', '12:30', '13:35', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Nha Trang', 'CXR', 'Sân bay Quốc tế Cam Ranh', 'Cam Ranh International Airport', 'Bamboo Airways', '1h05m', '1.401.201', '1.372.962', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '20kg per item', '', '', 'QH 372', 'https://www.bambooairways.com/'),
	(51, 'https://i.postimg.cc/QCKYMrsD/Vietravel-Airlines-Logo.png', 'https://i.postimg.cc/3wJTxWqH/viet-Travel-Airplane-removebg-preview.png', '14:40', '15:55', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Nha Trang', 'CXR', 'Sân bay Quốc tế Cam Ranh', 'Cam Ranh International Airport', 'Vietravel Airlines', '1h15m', '1.452.019', '1.432.010', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '15kg per item', '', '', 'VU 814', 'https://www.vietravelairlines.com/'),
	(52, 'https://i.postimg.cc/NGN8Sf9V/Vn-Airlines.png', 'https://i.postimg.cc/nrxWWVXM/Vn-Airlines-Airplane-removebg-preview.png', '16:05', '17:05', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Nha Trang', 'CXR', 'Sân bay Quốc tế Cam Ranh', 'Cam Ranh International Airport', 'Vietnam Airlines', '1h00m', '1.545.873', '1.520.938', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '25kg per item', '', '', 'VN 890', 'https://www.vietnamairlines.com/'),
	(53, 'https://i.postimg.cc/NGN8Sf9V/Vn-Airlines.png', 'https://i.postimg.cc/nrxWWVXM/Vn-Airlines-Airplane-removebg-preview.png', '18:05', '19:15', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Nha Trang', 'CXR', 'Sân bay Quốc tế Cam Ranh', 'Cam Ranh International Airport', 'Vietnam Airlines', '1h00m', '1.758.322', '1.730.020', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '25kg per item', '', '', 'VN 900', 'https://www.vietnamairlines.com/'),
	(54, 'https://i.postimg.cc/ZYytchFh/vietjet-Air.png', 'https://i.postimg.cc/BbWqgZjX/Vietjet-Air-Airplane-removebg-preview.png', '20:50', '22:00', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Nha Trang', 'CXR', 'Sân bay Quốc tế Cam Ranh', 'Cam Ranh International Airport', 'Vietjet Air', '1h10m', '1.421.929', '1.400.002', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '15kg per item', '', '', 'VJ 234', 'https://www.vietjetair.com/'),
	(55, 'https://i.postimg.cc/t4zWg7c9/Jetstar-Pacific-logo-removebg-preview.png', 'https://i.postimg.cc/Bvx5HMtf/Jetstar-Pacific-airplane-removebg-preview.png', '22:40', '23:50', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Nha Trang', 'CXR', 'Sân bay Quốc tế Cam Ranh', 'Cam Ranh International Airport', 'Jetstar Pacific', '1h10m', '1.480.912', '1.464.020', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '15kg per item', '', '', 'BL 1100', 'https://www.jetstar.com/'),
	(57, 'https://i.postimg.cc/ZYytchFh/vietjet-Air.png', 'https://i.postimg.cc/BbWqgZjX/Vietjet-Air-Airplane-removebg-preview.png', '05:35', '10:45', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Tokyo', 'HND', 'Sân bay Haneda', 'Haneda Airport', 'Vietjet Air', '5h10m', '2.777.192', '2.741.292', 'Direct', 'Basic', '1 piece per person, 10kg per piece', '15kg per item', 'Cheapest', 'Fastest', 'VJ 8080', 'https://www.vietjetair.com/'),
	(58, 'https://i.postimg.cc/ZYytchFh/vietjet-Air.png', 'https://i.postimg.cc/BbWqgZjX/Vietjet-Air-Airplane-removebg-preview.png', '06:10', '11:40', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Tokyo', 'HND', 'Sân bay Haneda', 'Haneda Airport', 'Vietjet Air', '5h30m', '2.672.601', '2.633.101', 'Direct', 'Basic', '1 piece per person, 10kg per piece', '15kg per item', '', '', 'VJ 8081', 'https://www.vietjetair.com/'),
	(59, 'https://i.postimg.cc/NGN8Sf9V/Vn-Airlines.png', 'https://i.postimg.cc/nrxWWVXM/Vn-Airlines-Airplane-removebg-preview.png', '06:30', '12:00', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Tokyo', 'HND', 'Sân bay Haneda', 'Haneda Airport', 'Vietnam Airlines', '6h00m', '3.782.901', '3.730.102', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '25kg per item', '', '', 'VN 201', 'https://www.vietnamairlines.com/'),
	(60, 'https://i.postimg.cc/NGN8Sf9V/Vn-Airlines.png', 'https://i.postimg.cc/nrxWWVXM/Vn-Airlines-Airplane-removebg-preview.png', '09:40', '15:40', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Tokyo', 'HND', 'Sân bay Haneda', 'Haneda Airport', 'Vietnam Airlines', '6h00m', '3.782.901', '3.730.102', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '25kg per item', '', '', 'VN 211', 'https://www.vietnamairlines.com/'),
	(61, 'https://i.postimg.cc/X7Mm9Rcs/Scoot-Airline-logo-removebg-preview.png', 'https://i.postimg.cc/mgjY29gQ/Scoot-Airlines-airplane-removebg-preview.png', '10:50', '17:00', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Tokyo', 'HND', 'Sân bay Haneda', 'Haneda Airport', 'Scoot Airlines', '6h10m', '3.910.900', '3.900.910', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '25kg per item', '', '', 'TR 221', 'https://flights.flyscoot.com/'),
	(64, 'https://i.postimg.cc/ZRtbtq5S/Cathay-Pacific-Airways-logo-removebg-preview.png', 'https://i.postimg.cc/nzGtyYW4/Cathay-pacific-airplane-removebg-preview.png', '12:55', '00:00', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Tokyo', 'HND', 'Sân bay Haneda', 'Haneda Airport', 'Cathay Pacific', '11h55m', '8.210.904', '8.200.464', '2 Steps', 'Business', '1 piece per person, 25kg per piece', '25kg per item', '', '', 'CX 2000', 'https://www.cathaypacific.com/'),
	(65, 'https://i.postimg.cc/wBCJvQLb/China-Southern-Airlines-logo-removebg-preview.png', 'https://i.postimg.cc/8zTZkNNr/China-Southern-Airlines-airplane-removebg-preview.png', '14:35', '02:35', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Tokyo', 'HND', 'Sân bay Haneda', 'Haneda Airport', 'China Southen Airlines', '12h00m', '12.210.904', '12.200.464', '2 Steps', 'Business', '1 piece per person, 10kg per piece', '25kg per item', 'Deluxe', 'Comfort', 'CZ 3000', 'https://oversea.csair.com/'),
	(66, 'https://i.postimg.cc/hjGjKJ33/Japan-Airlines.png', 'https://i.postimg.cc/tgBqvqCd/Japan-Airlines-Airplane-removebg-preview.png', '17:10', '04:35', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Tokyo', 'HND', 'Sân bay Haneda', 'Haneda Airport', 'Japan Airlines', '14h00m', '14.110.904', '14.080.464', '2 Steps', 'Premium ', '1 piece per person, 10kg per piece', '25kg per item', 'Deluxe', 'Comfort', 'JL 1027', 'https://www.jal.co.jp/vn/en/'),
	(67, 'https://i.postimg.cc/t418G95t/ANA-logo.jpg', 'https://i.postimg.cc/XYp6NfV5/All-Nippon-Airways-Airplane-removebg-preview.png', '19:45', '12:45', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Tokyo', 'HND', 'Sân bay Haneda', 'Haneda Airport', 'All Nippon Airways', '17h00m', '16.410.904', '16.320.029', '3 Steps', 'Premium ', '1 piece per person, 10kg per piece', '40kg per item', 'Deluxe', 'Super Comfort', 'NH 1027', 'https://www.ana.co.jp/en/us/'),
	(68, 'https://i.postimg.cc/MGSn8tTH/emitares-airline-logo.png', 'https://i.postimg.cc/XYp6NfV5/All-Nippon-Airways-Airplane-removebg-preview.png', '21:30', '10:45', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Tokyo', 'HND', 'Sân bay Haneda', 'Haneda Airport', 'Emirates Airline', '13h15m', '18.201.904', '18.145.029', '2 Steps', 'Premium ', '1 piece per person, 10kg per piece', '40kg per item', 'Deluxe', 'Super Comfort', 'EK 105', 'https://www.emirates.com/'),
	(69, 'https://i.postimg.cc/90t3n2Gt/Shenzhen-Airlines-China-logo-removebg-preview.png', 'https://i.postimg.cc/d3vdYRyP/Shenzhen-Airlines-airplane-removebg-preview.png', '23:35', '11:45', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Tokyo', 'HND', 'Sân bay Haneda', 'Haneda Airport', 'Shenzhen Airlines', '12h10m', '14.301.904', '14.235.029', '2 Steps', 'Premium ', '1 piece per person, 10kg per piece', '30kg per item', 'Deluxe', 'Comfort', 'ZH 2023', 'https://global.shenzhenair.com/zhair/ibe/common/flightSearch.do?language=en&market=CN'),
	(70, 'https://i.postimg.cc/ZYytchFh/vietjet-Air.png', 'https://i.postimg.cc/BbWqgZjX/Vietjet-Air-Airplane-removebg-preview.png', '01:20', '08:30', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Osaka', 'KIX', 'Sân bay Quốc tế Kansai', 'Kansai International Airport', 'Vietjet Air', '7h10m', '3.717.279', '3.715.202', 'Direct', 'Basic', '1 piece per person, 10kg per piece', '15kg per item', 'Cheapest', '', 'VJ 717', 'https://www.vietjetair.com/'),
	(71, 'https://i.postimg.cc/t418G95t/ANA-logo.jpg', 'https://i.postimg.cc/XYp6NfV5/All-Nippon-Airways-Airplane-removebg-preview.png', '03:10', '10:20', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Osaka', 'KIX', 'Sân bay Quốc tế Kansai', 'Kansai International Airport', 'All Nippon Airways', '7h10m', '23.289.279', '23.231.202', 'Direct', 'Premium ', '1 piece per person, 10kg per piece', '40kg per item', 'Deluxe', 'Super Comfort', 'NH 2024', 'https://www.ana.co.jp/en/us/'),
	(74, 'https://i.postimg.cc/NGN8Sf9V/Vn-Airlines.png', 'https://i.postimg.cc/nrxWWVXM/Vn-Airlines-Airplane-removebg-preview.png', '05:20', '13:30', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Osaka', 'KIX', 'Sân bay Quốc tế Kansai', 'Kansai International Airport', 'Vietnam Airlines', '8h30m', '8.821.893', '8.764.020', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '25kg per item', '', '', 'VN 2024', 'https://www.vietnamairlines.com/'),
	(75, 'https://i.postimg.cc/90t3n2Gt/Shenzhen-Airlines-China-logo-removebg-preview.png', 'https://i.postimg.cc/d3vdYRyP/Shenzhen-Airlines-airplane-removebg-preview.png', '06:45', '14:45', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Osaka', 'KIX', 'Sân bay Quốc tế Kansai', 'Kansai International Airport', 'Shenzhen Airlines', '8h00m', '12.202.101', '12.176.483', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '30kg per item', '', 'Comfort', 'ZH 217', 'https://global.shenzhenair.com/zhair/ibe/common/flightSearch.do?language=en&market=CN'),
	(76, 'https://i.postimg.cc/xdmsJpjQ/Cambodia-Angkor-Air-Cambodia-removebg-preview.png', 'https://i.postimg.cc/TYhpJZzr/Cambodia-Angkor-Air-airplane-removebg-preview.png', '08:30', '15:00', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Osaka', 'KIX', 'Sân bay Quốc tế Kansai', 'Kansai International Airport', 'Cambodia Angkor Air', '6h30m', '10.092.101', '10.050.210', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '30kg per item', '', '', 'K6 217', 'https://www.cambodiaangkorair.com/'),
	(77, 'https://i.postimg.cc/ZRtbtq5S/Cathay-Pacific-Airways-logo-removebg-preview.png', 'https://i.postimg.cc/nzGtyYW4/Cathay-pacific-airplane-removebg-preview.png', '10:45', '18:05', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Osaka', 'KIX', 'Sân bay Quốc tế Kansai', 'Kansai International Airport', 'Cathay Pacific', '7h30m', '14.092.019', '13.980.101', 'Direct', 'Business', '1 piece per person, 25kg per piece', '25kg per item', '', 'Comfort', 'CX 100', 'https://www.cathaypacific.com/'),
	(78, 'https://i.postimg.cc/X7Mm9Rcs/Scoot-Airline-logo-removebg-preview.png', 'https://i.postimg.cc/mgjY29gQ/Scoot-Airlines-airplane-removebg-preview.png', '15:30', '23:30', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Osaka', 'KIX', 'Sân bay Quốc tế Kansai', 'Kansai International Airport', 'Scoot Airlines', '8h00m', '12.453.281', '12.409.576', '2 Steps', 'Business', '1 piece per person, 10kg per piece', '25kg per item', '', 'Comfort', 'TR 4021', 'https://flights.flyscoot.com/'),
	(79, 'https://i.postimg.cc/wBCJvQLb/China-Southern-Airlines-logo-removebg-preview.png', 'https://i.postimg.cc/8zTZkNNr/China-Southern-Airlines-airplane-removebg-preview.png', '19:45', '08:45', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Osaka', 'KIX', 'Sân bay Quốc tế Kansai', 'Kansai International Airport', 'China Southen Airlines', '13h00m', '15.213.281', '15.159.516', '2 Steps', 'Premium ', '1 piece per person, 10kg per piece', '25kg per item', 'Deluxe', 'Comfort', 'CZ 101', 'https://oversea.csair.com/'),
	(80, 'https://i.postimg.cc/hjGjKJ33/Japan-Airlines.png', 'https://i.postimg.cc/tgBqvqCd/Japan-Airlines-Airplane-removebg-preview.png', '21:30', '12:45', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Osaka', 'KIX', 'Sân bay Quốc tế Kansai', 'Kansai International Airport', 'Japan Airlines', '15h15m', '24.320.854', '24.243.921', '3 Steps', 'Premium ', '1 piece per person, 10kg per piece', '25kg per item', 'Deluxe', 'Super Comfort', 'JL 208', 'https://www.jal.co.jp/vn/en/'),
	(81, 'https://i.postimg.cc/NGN8Sf9V/Vn-Airlines.png', 'https://i.postimg.cc/nrxWWVXM/Vn-Airlines-Airplane-removebg-preview.png', '23:30', '07:45', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Osaka', 'KIX', 'Sân bay Quốc tế Kansai', 'Kansai International Airport', 'Vietnam Airlines', '8h15m', '10.023.011', '10.982.010', 'Direct', 'Premium ', '1 piece per person, 10kg per piece', '25kg per item', 'Deluxe', 'Comfort', 'VN 2011', 'https://www.vietnamairlines.com/'),
	(82, 'https://i.postimg.cc/vBdHpvQh/EVA-Air-logo-removebg-preview.png', 'https://i.postimg.cc/DfNsMt9P/EVA-airplane-removebg-preview.png', '01:25', '09:25', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Osaka', 'KIX', 'Sân bay Quốc tế Kansai', 'Kansai International Airport', 'EVA Air', '8h00m', '13.472.918', '13.421.894', 'Direct', 'Premium ', '1 piece per person, 20kg per piece', '35kg per item', 'Deluxe', 'Comfort', 'BR 1010', 'https://www.evaair.com/'),
	(83, 'https://i.postimg.cc/ZYytchFh/vietjet-Air.png', 'https://i.postimg.cc/BbWqgZjX/Vietjet-Air-Airplane-removebg-preview.png', '04:30', '07:00', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Bangkok', 'BKK', 'Sân bay Suvarnabhumi', 'Suvarnabhumi Airport', 'Vietjet Air', '2h30m', '2.024.201', '2.004.150', 'Direct', 'Basic', '1 piece per person, 10kg per piece', '25kg per item', 'Cheapest', '', 'VJ 621', 'https://www.vietjetair.com/'),
	(84, 'https://i.postimg.cc/QCKYMrsD/Vietravel-Airlines-Logo.png', 'https://i.postimg.cc/3wJTxWqH/viet-Travel-Airplane-removebg-preview.png', '06:30', '09:00', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Bangkok', 'BKK', 'Sân bay Suvarnabhumi', 'Suvarnabhumi Airport', 'Vietravel Airlines', '2h30m', '2.418.822', '2.401.201', 'Direct', 'Basic', '1 piece per person, 10kg per piece', '15kg per item', '', '', 'VU 699', 'https://www.vietravelairlines.com/'),
	(85, 'https://i.postimg.cc/X7Mm9Rcs/Scoot-Airline-logo-removebg-preview.png', 'https://i.postimg.cc/mgjY29gQ/Scoot-Airlines-airplane-removebg-preview.png', '08:30', '11:15', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Bangkok', 'BKK', 'Sân bay Suvarnabhumi', 'Suvarnabhumi Airport', 'Scoot Airlines', '2h45m', '2.781.201', '2.707.120', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '25kg per item', '', '', 'TR 990', 'https://flights.flyscoot.com/'),
	(86, 'https://i.postimg.cc/NGN8Sf9V/Vn-Airlines.png', 'https://i.postimg.cc/nrxWWVXM/Vn-Airlines-Airplane-removebg-preview.png', '09:40', '12:30', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Bangkok', 'BKK', 'Sân bay Suvarnabhumi', 'Suvarnabhumi Airport', 'Vietnam Airlines', '2h50m', '2.810.201', '2.801.444', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '25kg per item', '', '', 'VN 2771', 'https://www.vietnamairlines.com/'),
	(87, 'https://i.postimg.cc/xdmsJpjQ/Cambodia-Angkor-Air-Cambodia-removebg-preview.png', 'https://i.postimg.cc/TYhpJZzr/Cambodia-Angkor-Air-airplane-removebg-preview.png', '12:30', '15:00', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Bangkok', 'BKK', 'Sân bay Suvarnabhumi', 'Suvarnabhumi Airport', 'Cambodia Angkor Air', '2h30m', '3.112.094', '3.100.457', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '30kg per item', '', '', 'K6 8712', 'https://www.cambodiaangkorair.com/'),
	(88, 'https://i.postimg.cc/wBCJvQLb/China-Southern-Airlines-logo-removebg-preview.png', 'https://i.postimg.cc/8zTZkNNr/China-Southern-Airlines-airplane-removebg-preview.png', '14:30', '21:30', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Bangkok', 'BKK', 'Sân bay Suvarnabhumi', 'Suvarnabhumi Airport', 'China Southen Airlines', '7h30m', '6.453.291', '6.400.201', '2 Steps', 'Economy', '1 piece per person, 10kg per piece', '25kg per item', '', '', 'CZ 9101', 'https://oversea.csair.com/'),
	(89, 'https://i.postimg.cc/vZbxck56/HK-Express-Logo-removebg-preview.png', 'https://i.postimg.cc/7hJYWM04/HK-Express-airplane-removebg-preview.png', '16:00', '19:30', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Bangkok', 'BKK', 'Sân bay Suvarnabhumi', 'Suvarnabhumi Airport', 'HK Express', '3h30m', '4.101.201', '4.082.564', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '25kg per item', '', 'Comfort', 'UO 123', 'https://www.hkexpress.com/en-hk/'),
	(90, 'https://i.postimg.cc/90t3n2Gt/Shenzhen-Airlines-China-logo-removebg-preview.png', 'https://i.postimg.cc/d3vdYRyP/Shenzhen-Airlines-airplane-removebg-preview.png', '17:45', '21:15', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Bangkok', 'BKK', 'Sân bay Suvarnabhumi', 'Suvarnabhumi Airport', 'Shenzhen Airlines', '3h30m', '5.230.201', '5.200.456', 'Direct', 'Business', '1 piece per person, 10kg per piece', '30kg per item', '', 'Comfort', 'ZH 291', 'https://global.shenzhenair.com/zhair/ibe/common/flightSearch.do?language=en&market=CN'),
	(91, 'https://i.postimg.cc/3RRgWV5Z/Malaysia-Airlines-Logo-removebg-preview.png', 'https://i.postimg.cc/MZnFFrMR/Malaysia-Airlines-airplane-removebg-preview.png', '19:30', '03:50', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Bangkok', 'BKK', 'Sân bay Suvarnabhumi', 'Suvarnabhumi Airport', 'Malaysia Airlines', '8h30m', '8.040.289', '8.023.674', '2 Steps', 'Business', '1 piece per person, 10kg per piece', '30kg per item', '', 'Comfort', 'MH 301', 'https://www.malaysiaairlines.com/my/en/home.html'),
	(92, 'https://i.postimg.cc/MKQKqD4f/Air-China-China-logo-removebg-preview.png', 'https://i.postimg.cc/vTDTrw30/Air-china-airplane-removebg-preview.png', '21:00', '06:00', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Bangkok', 'BKK', 'Sân bay Suvarnabhumi', 'Suvarnabhumi Airport', 'Air China', '9h00m', '10.471.011', '10.432.574', '2 Steps', 'Premium ', '1 piece per person, 10kg per piece', '30kg per item', 'Deluxe', 'Comfort', 'CA 2048', 'https://www.airchina.co.uk/GB/GB/Home'),
	(93, 'https://i.postimg.cc/L6wtqSts/Delta-Air-Lines-logos-removebg-preview.png', 'https://i.postimg.cc/5yZXtxhd/Delta-Air-Lines-airplane-removebg-preview-1.png', '23:00', '08:00', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Bangkok', 'BKK', 'Sân bay Suvarnabhumi', 'Suvarnabhumi Airport', 'Delta Airlines', '9h00m', '11.382.019', '11.330.573', 'Direct', 'Premium ', '1 piece per person, 10kg per piece', '30kg per item', 'Deluxe', 'Comfort', 'DL 1001', 'https://www.delta.com/'),
	(94, 'https://i.postimg.cc/ZYytchFh/vietjet-Air.png', 'https://i.postimg.cc/BbWqgZjX/Vietjet-Air-Airplane-removebg-preview.png', '08:50', '12:05', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Singapore', 'SIN', 'Sân bay Changi Singapore', 'Changi Singapore Airport', 'Vietjet Air', '4h15m', '1.395.201', '1.390.201', 'Direct', 'Basic', '1 piece per person, 10kg per piece', '15kg per item', 'Cheapest', '', 'VJ 9009', 'https://www.vietjetair.com/'),
	(95, 'https://i.postimg.cc/X7Mm9Rcs/Scoot-Airline-logo-removebg-preview.png', 'https://i.postimg.cc/mgjY29gQ/Scoot-Airlines-airplane-removebg-preview.png', '10:30', '14:00', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Singapore', 'SIN', 'Sân bay Changi Singapore', 'Changi Singapore Airport', 'Scoot Airlines', '3h30m', '2.617.019', '2.600.566', 'Direct', 'Basic', '1 piece per person, 10kg per piece', '25kg per item', '', 'Fastest', 'TR 1011', 'https://flights.flyscoot.com/'),
	(96, 'https://i.postimg.cc/NGN8Sf9V/Vn-Airlines.png', 'https://i.postimg.cc/nrxWWVXM/Vn-Airlines-Airplane-removebg-preview.png', '11:45', '15:45', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Singapore', 'SIN', 'Sân bay Changi Singapore', 'Changi Singapore Airport', 'Vietnam Airlines', '4h00m', '3.027.981', '3.000.116', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '25kg per item', '', '', 'VN 2020', 'http://www.vietnamairlines.com/'),
	(97, 'https://i.postimg.cc/t4zWg7c9/Jetstar-Pacific-logo-removebg-preview.png', 'https://i.postimg.cc/Bvx5HMtf/Jetstar-Pacific-airplane-removebg-preview.png', '13:00', '17:00', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Singapore', 'SIN', 'Sân bay Changi Singapore', 'Changi Singapore Airport', 'Jetstar Pacific', '4h00m', '2.819.019', '2.802.533', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '15kg per item', '', '', 'BL 911', 'https://www.jetstar.com/'),
	(98, 'https://i.postimg.cc/CKPL1h8P/Singapore-Airlines-Logo-removebg-preview.png', 'https://i.postimg.cc/tJdKskfq/Singapore-Airlines-airplane-removebg-preview.png', '14:30', '18:30', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Singapore', 'SIN', 'Sân bay Changi Singapore', 'Changi Singapore Airport', 'Singapore Airlines', '4h00m', '4.264.382', '4.210.472', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '25kg per item', '', 'Comfort', 'SQ 891', 'https://www.singaporeair.com/'),
	(99, 'https://i.postimg.cc/CKPL1h8P/Singapore-Airlines-Logo-removebg-preview.png', 'https://i.postimg.cc/tJdKskfq/Singapore-Airlines-airplane-removebg-preview.png', '15:00', '19:00', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Singapore', 'SIN', 'Sân bay Changi Singapore', 'Changi Singapore Airport', 'Singapore Airlines', '4h00m', '4.264.382', '4.210.472', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '25kg per item', '', 'Comfort', 'SQ 431', 'https://www.singaporeair.com/'),
	(100, 'https://i.postimg.cc/CKPL1h8P/Singapore-Airlines-Logo-removebg-preview.png', 'https://i.postimg.cc/tJdKskfq/Singapore-Airlines-airplane-removebg-preview.png', '15:30', '19:30', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Singapore', 'SIN', 'Sân bay Changi Singapore', 'Changi Singapore Airport', 'Singapore Airlines', '4h00m', '4.264.382', '4.210.472', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '25kg per item', '', 'Comfort', 'SQ 990', 'https://www.singaporeair.com/'),
	(101, 'https://i.postimg.cc/wBCJvQLb/China-Southern-Airlines-logo-removebg-preview.png', 'https://i.postimg.cc/8zTZkNNr/China-Southern-Airlines-airplane-removebg-preview.png', '17:50', '22:00', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Singapore', 'SIN', 'Sân bay Changi Singapore', 'Changi Singapore Airport', 'China Southen Airlines', '4h10m', '7.829.011', '7.814.099', 'Direct', 'Business', '1 piece per person, 10kg per piece', '25kg per item', '', 'Comfort', 'CZ 3772', 'https://oversea.csair.com/'),
	(102, 'https://i.postimg.cc/xdmsJpjQ/Cambodia-Angkor-Air-Cambodia-removebg-preview.png', 'https://i.postimg.cc/TYhpJZzr/Cambodia-Angkor-Air-airplane-removebg-preview.png', '19:00', '23:00', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Singapore', 'SIN', 'Sân bay Changi Singapore', 'Changi Singapore Airport', 'Cambodia Angkor Air', '4h00m', '5.299.463', '5.201.574', 'Direct', 'Business', '1 piece per person, 10kg per piece', '30kg per item', '', 'Comfort', 'K6 111', 'https://www.cambodiaangkorair.com/'),
	(103, 'https://i.postimg.cc/ZRtbtq5S/Cathay-Pacific-Airways-logo-removebg-preview.png', 'https://i.postimg.cc/nzGtyYW4/Cathay-pacific-airplane-removebg-preview.png', '20:00', '00:15', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Singapore', 'SIN', 'Sân bay Changi Singapore', 'Changi Singapore Airport', 'Cathay Pacific', '4h15m', '6.998.727', '6.950.012', 'Direct', 'Business', '1 piece per person, 25kg per piece', '30kg per item', '', 'Comfort', 'CX 991', 'https://www.cathaypacific.com/'),
	(104, 'https://i.postimg.cc/vBdHpvQh/EVA-Air-logo-removebg-preview.png', 'https://i.postimg.cc/DfNsMt9P/EVA-airplane-removebg-preview.png', '21:30', '03:30', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Singapore', 'SIN', 'Sân bay Changi Singapore', 'Changi Singapore Airport', 'EVA Air', '6h00m', '10.120.009', '10.101.573', '2 Steps', 'Premium ', '1 piece per person, 25kg per piece', '30kg per item', 'Deluxe', 'Comfort', 'BR 9900', 'https://www.evaair.com/'),
	(105, 'https://i.postimg.cc/m2ZZFHm8/T-way-Airlines-Logo-removebg-preview.png', 'https://i.postimg.cc/HnYm5q9V/T-way-Airlines-Airplane-removebg-preview-1.png', '23:50', '07:00', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Singapore', 'SIN', 'Sân bay Changi Singapore', 'Changi Singapore Airport', 'TWay Airlines', '7h10m', '5.303.111', '5.266.101', '2 Steps', 'Business', '1 piece per person, 25kg per piece', '30kg per item', '', '', 'TW 1001', 'https://www.twayair.com/app/main?regionCode=KR&langCode=en-US'),
	(106, 'https://i.postimg.cc/3RRgWV5Z/Malaysia-Airlines-Logo-removebg-preview.png', 'https://i.postimg.cc/MZnFFrMR/Malaysia-Airlines-airplane-removebg-preview.png', '06:00', '09:00', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Kuala Lumpur', 'KUL', 'Sân bay quốc tế Kuala Lumpur', 'Kuala Lumpur International Airport', 'Malaysia Airlines', '3h00m', '1.799.929', '1.789.202', 'Direct', 'Economy', '1 piece per person, 25kg per piece', '30kg per item', 'Cheapest', '', 'MH 200', 'https://www.malaysiaairlines.com/my/en/home.html'),
	(107, 'https://i.postimg.cc/1zjvpn2F/world2fly-logo-removebg-preview.png', 'https://i.postimg.cc/DzZCJdjF/World-2-fly-airplane-removebg-preview.png', '07:30', '10:00', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Kuala Lumpur', 'KUL', 'Sân bay quốc tế Kuala Lumpur', 'Kuala Lumpur International Airport', 'World 2 Fly', '2h30m', '4.221.929', '4.190.000', 'Direct', 'Economy', '1 piece per person, 25kg per piece', '30kg per item', '', 'Fastest', '2W 301', 'https://www.w2fly.es/en-en'),
	(108, 'https://i.postimg.cc/QCKYMrsD/Vietravel-Airlines-Logo.png', 'https://i.postimg.cc/3wJTxWqH/viet-Travel-Airplane-removebg-preview.png', '08:30', '11:30', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Kuala Lumpur', 'KUL', 'Sân bay quốc tế Kuala Lumpur', 'Kuala Lumpur International Airport', 'Vietravel Airlines', '3h00m', '2.221.220', '2.210.555', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '15kg per item', '', '', 'VU 734', 'https://www.vietravelairlines.com/'),
	(109, 'https://i.postimg.cc/NGN8Sf9V/Vn-Airlines.png', 'https://i.postimg.cc/nrxWWVXM/Vn-Airlines-Airplane-removebg-preview.png', '09:40', '13:00', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Kuala Lumpur', 'KUL', 'Sân bay quốc tế Kuala Lumpur', 'Kuala Lumpur International Airport', 'Vietnam Airlines', '3h20m', '2.576.321', '2.555.482', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '25kg per item', '', '', 'VN 2317', 'https://www.vietnamairlines.com/'),
	(110, 'https://i.postimg.cc/X7Mm9Rcs/Scoot-Airline-logo-removebg-preview.png', 'https://i.postimg.cc/mgjY29gQ/Scoot-Airlines-airplane-removebg-preview.png', '10:30', '13:30', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Kuala Lumpur', 'KUL', 'Sân bay quốc tế Kuala Lumpur', 'Kuala Lumpur International Airport', 'Scoot Airlines', '3h00m', '2.745.333', '2.720.363', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '25kg per item', '', '', 'TR 1074', 'https://flights.flyscoot.com/'),
	(111, 'https://i.postimg.cc/xdmsJpjQ/Cambodia-Angkor-Air-Cambodia-removebg-preview.png', 'https://i.postimg.cc/TYhpJZzr/Cambodia-Angkor-Air-airplane-removebg-preview.png', '12:00', '15:10', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Kuala Lumpur', 'KUL', 'Sân bay quốc tế Kuala Lumpur', 'Kuala Lumpur International Airport', 'Cambodia Angkor Air', '3h10m', '2.980.777', '2.922.373', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '30kg per item', '', '', 'K6 7000', 'https://www.cambodiaangkorair.com/'),
	(112, 'https://i.postimg.cc/rwpGQySN/Air-asia-logo-removebg-preview.png', 'https://i.postimg.cc/vZSrjRhF/Air-Asia-airplane-removebg-preview.png', '13:15', '16:00', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Kuala Lumpur', 'KUL', 'Sân bay quốc tế Kuala Lumpur', 'Kuala Lumpur International Airport', 'Air Asia', '2h45m', '2.318.829', '2.300.563', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '30kg per item', '', '', 'AK 1001', 'https://www.airasia.com/vi/vn'),
	(113, 'https://i.postimg.cc/rwpGQySN/Air-asia-logo-removebg-preview.png', 'https://i.postimg.cc/vZSrjRhF/Air-Asia-airplane-removebg-preview.png', '14:00', '17:00', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Kuala Lumpur', 'KUL', 'Sân bay quốc tế Kuala Lumpur', 'Kuala Lumpur International Airport', 'Air Asia', '3h00m', '2.318.829', '2.300.563', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '30kg per item', '', '', 'QZ 1010', 'https://www.airasia.com/vi/vn'),
	(114, 'https://i.postimg.cc/rwpGQySN/Air-asia-logo-removebg-preview.png', 'https://i.postimg.cc/vZSrjRhF/Air-Asia-airplane-removebg-preview.png', '15:00', '18:00', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Kuala Lumpur', 'KUL', 'Sân bay quốc tế Kuala Lumpur', 'Kuala Lumpur International Airport', 'Air Asia', '3h00m', '2.318.829', '2.300.563', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '30kg per item', '', '', 'QZ 1011', 'https://www.airasia.com/vi/vn'),
	(115, 'https://i.postimg.cc/MKQKqD4f/Air-China-China-logo-removebg-preview.png', 'https://i.postimg.cc/vTDTrw30/Air-china-airplane-removebg-preview.png', '16:15', '19:30', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Kuala Lumpur', 'KUL', 'Sân bay quốc tế Kuala Lumpur', 'Kuala Lumpur International Airport', 'Air China', '3h15m', '5.685.393', '5.660.111', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '30kg per item', '', '', 'CA 1048', 'https://www.airchina.co.uk/GB/GB/Home'),
	(116, 'https://i.postimg.cc/QCKYMrsD/Vietravel-Airlines-Logo.png', 'https://i.postimg.cc/3wJTxWqH/viet-Travel-Airplane-removebg-preview.png', '17:00', '20:00', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Kuala Lumpur', 'KUL', 'Sân bay quốc tế Kuala Lumpur', 'Kuala Lumpur International Airport', 'Vietravel Airlines', '3h00m', '2.521.017', '2.500.201', 'Direct', 'Economy', '1 piece per person, 10kg per piece', '15kg per item', '', '', 'VU 123', 'https://www.vietravelairlines.com/'),
	(117, 'https://i.postimg.cc/pLg9zPkT/Philippine-Airlines-logo-removebg-preview.png', 'https://i.postimg.cc/0y6MzzYF/Philippine-Airlines-airplane-removebg-preview.png', '18:30', '21:30', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Kuala Lumpur', 'KUL', 'Sân bay quốc tế Kuala Lumpur', 'Kuala Lumpur International Airport', 'Philippine Airlines', '3h00m', '4.332.811', '4.300.573', 'Direct', 'Business', '1 piece per person, 10kg per piece', '25kg per item', '', '', 'PR 980', 'https://flights.philippineairlines.com/en/'),
	(118, 'https://i.postimg.cc/pLg9zPkT/Philippine-Airlines-logo-removebg-preview.png', 'https://i.postimg.cc/0y6MzzYF/Philippine-Airlines-airplane-removebg-preview.png', '19:30', '22:30', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Kuala Lumpur', 'KUL', 'Sân bay quốc tế Kuala Lumpur', 'Kuala Lumpur International Airport', 'Philippine Airlines', '3h00m', '4.345.811', '4.320.573', 'Direct', 'Business', '1 piece per person, 10kg per piece', '25kg per item', '', '', 'PR 323', 'https://flights.philippineairlines.com/en/'),
	(119, 'https://i.postimg.cc/pLg9zPkT/Philippine-Airlines-logo-removebg-preview.png', 'https://i.postimg.cc/0y6MzzYF/Philippine-Airlines-airplane-removebg-preview.png', '20:00', '23:15', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Kuala Lumpur', 'KUL', 'Sân bay quốc tế Kuala Lumpur', 'Kuala Lumpur International Airport', 'Philippine Airlines', '3h15m', '4.720.082', '4.700.211', 'Direct', 'Business', '1 piece per person, 10kg per piece', '25kg per item', '', '', 'PR 7799', 'https://flights.philippineairlines.com/en/'),
	(120, 'https://i.postimg.cc/KYPYTBRq/Thai-airways-logo-removebg-preview.png', 'https://i.postimg.cc/G2zh7RPv/Thai-Airways-airplane-removebg-preview.png', '20:45', '23:45', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Kuala Lumpur', 'KUL', 'Sân bay quốc tế Kuala Lumpur', 'Kuala Lumpur International Airport', 'Thai Airways', '3h00m', '6.270.191', '6.222.112', 'Direct', 'Business', '1 piece per person, 10kg per piece', '25kg per item', '', '', 'TG 920', 'https://www.thaiairways.com/'),
	(121, 'https://i.postimg.cc/KYPYTBRq/Thai-airways-logo-removebg-preview.png', 'https://i.postimg.cc/G2zh7RPv/Thai-Airways-airplane-removebg-preview.png', '21:30', '00:30', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Kuala Lumpur', 'KUL', 'Sân bay quốc tế Kuala Lumpur', 'Kuala Lumpur International Airport', 'Thai Airways', '3h00m', '6.350.101', '6.322.595', 'Direct', 'Business', '1 piece per person, 10kg per piece', '25kg per item', '', '', 'TG 920', 'https://www.thaiairways.com/'),
	(122, 'https://i.postimg.cc/pr6VvB6T/Xiamen-Airlines-China-logo-removebg-preview.png', 'https://i.postimg.cc/kG4MLHwz/Xiamen-airline-airplane-removebg-preview.png', '22:00', '03:00', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Kuala Lumpur', 'KUL', 'Sân bay quốc tế Kuala Lumpur', 'Kuala Lumpur International Airport', 'Xiamen Airlines', '5h00m', '10.221.463', '10.100.292', '2 Steps', 'Premium ', '1 piece per person, 10kg per piece', '35kg per item', 'Deluxe', 'Comfort', 'MF 800', 'https://www.xiamenair.com/en-vn/'),
	(123, 'https://i.postimg.cc/k5mJ7Gfx/Garuda-Indonesia-logo-removebg-preview.png', 'https://i.postimg.cc/257zyYKg/Garuda-Indonesia-airplane-removebg-preview.png', '23:30', '08:30', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Kuala Lumpur', 'KUL', 'Sân bay quốc tế Kuala Lumpur', 'Kuala Lumpur International Airport', 'Garuda Airlines', '9h00m', '14.928.191', '14.900.468', '2 Steps', 'Premium ', '1 piece per person, 10kg per piece', '35kg per item', 'Deluxe', 'Comfort', 'GA 716', 'https://www.garuda-indonesia.com/oc/en/'),
	(124, 'https://i.postimg.cc/k5mJ7Gfx/Garuda-Indonesia-logo-removebg-preview.png', 'https://i.postimg.cc/257zyYKg/Garuda-Indonesia-airplane-removebg-preview.png', '00:30', '09:30', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Kuala Lumpur', 'KUL', 'Sân bay quốc tế Kuala Lumpur', 'Kuala Lumpur International Airport', 'Garuda Airlines', '9h00m', '14.928.191', '14.900.468', '2 Steps', 'Premium ', '1 piece per person, 10kg per piece', '35kg per item', 'Deluxe', 'Comfort', 'GA 720', 'https://www.garuda-indonesia.com/oc/en/'),
	(125, 'https://i.postimg.cc/zBQ4XP89/Royal-Brunei-logo-removebg-preview.png', 'https://i.postimg.cc/SR343xnY/Royal-Brunei-airplane-removebg-preview.png', '01:30', '14:30', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Kuala Lumpur', 'KUL', 'Sân bay quốc tế Kuala Lumpur', 'Kuala Lumpur International Airport', 'Royal Brunei Airlines', '13h00m', '23.221.584', '23.201.675', '3 Steps', 'Premium ', '1 piece per person, 25kg per piece', '40kg per item', 'Royal', 'Super Comfort', 'BI 003', 'https://www.flyroyalbrunei.com/brunei/en/'),
	(126, 'https://i.postimg.cc/ZYytchFh/vietjet-Air.png', 'https://i.postimg.cc/BbWqgZjX/Vietjet-Air-Airplane-removebg-preview.png', '09:30', '12:30', 'Hồ Chí Minh', 'SGN', 'Sân bay Quốc tế Tân Sơn Nhất', 'Tan Son Nhat International Airport', 'Jakarta', 'CGK', 'Sân bay quốc tế Soekarno-Hatta', 'Soekarno-Hatta International Airport', 'Vietjet Air', '3h00m', '2.409.584', '2.392.010', 'Direct', 'Basic', '1 piece per person, 10kg per piece', '15kg per item', 'Cheapest', '', 'VJ 321', 'https://www.vietjetair.com/');

-- Dumping structure for table flight.flight_searches
CREATE TABLE IF NOT EXISTS `flight_searches` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `departure` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci DEFAULT NULL,
  `destination` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci DEFAULT NULL,
  `start_date` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci DEFAULT NULL,
  `adult` int(11) DEFAULT NULL,
  `child` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=129 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

-- Dumping data for table flight.flight_searches: ~0 rows (approximately)

-- Dumping structure for table flight.user
CREATE TABLE IF NOT EXISTS `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `full_name` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `email` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  `password` varchar(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

-- Dumping data for table flight.user: ~4 rows (approximately)
INSERT INTO `user` (`id`, `full_name`, `email`, `password`) VALUES
	(1, 'Dongdung', 'Dongdung0407@gmail.com', 'dungcon2003'),
	(2, 'Tonton', 'Ton@gmail.com', '12345'),
	(3, 'Tuaton', 'Tonton@gmail.com', '12345'),
	(4, 'Haomai', 'anhdien12121@gmail.com', '1234567');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
